### PR TITLE
Subdir

### PR DESCRIPTION
**Pull request by mattmb**
Allows us to host the app on a subdirectory.

This will be /employment-tribunals. Or whatever's set as RAILS_RELATIVE_URL_ROOT.

Unfortunately we have a bunch of static links in our locale file. Is it rendered anywhere i.e. can we use the environment variable somehow?

### CODE REVIEW

**Comment by stevegraham** [comment]
I spoke to @tomwm before xmas and our app will be launched in parallel to Jadu's remaining in service, so ours can't be mounted at `/employment-tribunals` as this is taken by Jadu's.

I will close this after speaking to @helenmott, I remember there being another reason why we might need a prefix so I want to check first. If we need to maintain access to legacy pages we can proxy them in nginx.

**Comment by helenmott** [comment]
The other reason was there are a number of forms that sit within the
Employment Tribunal service (ours, the ET3 and the EAT), and each of these
would need their own URL.

On 5 January 2015 at 10:15, Stevie Graham <notifications@github.com> wrote:

> I spoke to @tomwm <https://github.com/tomwm> before xmas and our app will
> be launched in parallel to Jadu's remaining in service, so ours can't be
> mounted at /employment-tribunals as this is taken by Jadu's.
>
> I will close this after speaking to @helenmott
> <https://github.com/helenmott>, I remember there being another reason why
> we might need a prefix so I want to check first. If we need to maintain
> access to legacy pages we can proxy them in nginx.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ministryofjustice/atet/pull/429#issuecomment-68689341>
> .
>



-- 
Helen Mott
Head of Clan for Delivery
MoJ Digital Services
07712 667792

**Comment by stevegraham** [comment]
let's discuss after standup.

**Comment by mattmb** [comment]
@stevegraham I think there's also a connection with the links on gov.uk?

Also if there's going to be some period when we do coexist with Jadu then we'll still need this. Will be in after lunch if you want to discus.

**Pull request closed without merging**
